// Global Color Configuration for GL-B Group (generated by set-brand.js)

const colors = {
  primary: {
    main: '#26285b',
    light: '#383a85',
    dark: '#14142f',
    50: '#888bcd',
    100: '#6f72c3',
    200: '#5659b8',
    300: '#4548a5',
    400: '#3b3d8c',
    500: '#303273',
    600: '#26275a',
    700: '#1b1c41',
    800: '#111128',
    900: '#06060e',
  },
  secondary: {
    main: '#c9c6c2',
    light: '#e5e3e1',
    dark: '#aba6a0',
    50: '#ffffff',
    100: '#ffffff',
    200: '#ffffff',
    300: '#fafafa',
    400: '#e9e8e7',
    500: '#d9d7d4',
    600: '#c8c5c1',
    700: '#b7b3ae',
    800: '#a6a19b',
    900: '#969088',
  },
  neutral: {
    white: '#ffffff',
    gray: {
      50: '#f9fafb', 100: '#f3f4f6', 200: '#e5e7eb', 300: '#d1d5db', 400: '#9ca3af', 500: '#6b7280', 600: '#4b5563', 700: '#374151', 800: '#1f2937', 900: '#111827'
    },
    dark: '#0f172a',
  },
  success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#26275a'
}

const tailwindColors = { primary: colors.primary, secondary: colors.secondary, gray: colors.neutral.gray }

module.exports = { colors, tailwindColors }
