import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Services from '../components/Services'
import Contact from '../components/Contact'
import AboutUs from '../components/AboutUs'
import Products from '../components/Products'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GL-B GROUP SARL</title>
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Banner />
      <Services />
      <AboutUs />
      <Products />
      <Contact />
    </div>
  )
}
