import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic'
import Banner from '../components/Banner'
const Services = dynamic(() => import('../components/Services'), { ssr: false })
const AboutUs = dynamic(() => import('../components/AboutUs'), { ssr: false })
const Products = dynamic(() => import('../components/Products'), { ssr: false })
const Contact = dynamic(() => import('../components/Contact'), { ssr: false })

export default function Home() {
  return (
    <div>
      <Head>
        <title>GL-B GROUP SARL</title>
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Banner />
  <Services />
  <AboutUs />
  <Products />
  <Contact />
    </div>
  )
}
